package uleb128

import (
	"fmt"
	"testing"
)

func TestLength(t *testing.T) {
	testBytes := []byte("\x93\x03TestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnoreTestPlsIgnore")
	fmt.Println(Unmarshal(testBytes))
}
